### ISSUE TITLE
Readme polishing

### ISSUE THREAD

**Issue by Kreezag** [spiral/shopify-starter-kit#52]
Need to fix TYPO and grammar poings in readme description

**Comment by Leiloukou** [comment]
I could help, what line is the error on?

**Comment by Leiloukou** [comment]
I am trying to get started with open source contributing, so if you could tell me about the typo, I would like to fix it.
If you know of any javascript related issues, please tell me.

**Comment by Kreezag** [comment]
> I am trying to get started with open source contributing, so if you could tell me about the typo, I would like to fix it. If you know of any javascript related issues, please tell me.

Thanks for suggest. Your help not need yet. We already have the review of README, but we need to aplly the result.

**Comment by Leiloukou** [comment]
Ok, thanks.
